#pragma once
#include "SettingsUiModel.h"
#include <unordered_map>
namespace metasequoia::linux_ime
{
inline const char *row_label(const SettingsUiRow &row)
{
    static const std::unordered_map<std::string, const char *> labels = {
        {"mode", "输入模式"},
        {"scheme", "输入方案"},
        {"show-quanpin-helpcode", "候选显示全拼辅助码"},
        {"show-shuangpin-helpcode", "候选显示双拼辅助码"},
        {"switch-language-shift", "Shift 切换中英文"},
        {"switch-language-ctrl", "Ctrl 切换中英文"},
        {"switch-language-ctrl-alt-space", "Ctrl+Alt+空格切换中英文"},
        {"quick-phrase-mode", "快捷短语"},
        {"date-time-mode", "日期时间模式"},
        {"emoji-mode", "Emoji 模式"},
        {"kaomoji-mode", "颜文字模式"},
        {"page-size", "每页候选数"},
        {"candidate-window-layout", "候选窗口排列方式"},
        {"punctuation", "标点模式"},
        {"width", "字符宽度"},
        {"preedit-style", "预编辑样式"},
        {"comma-period-paging", "逗号/句号翻页"},
        {"word-to-character", "词转单字"},
        {"bracket-paging", "方括号翻页"},
        {"smart-punctuation", "智能标点"},
        {"smart-punctuation-repeat-to-chinese", "重复标点切换中文"},
        {"paired-punctuation", "成对标点"},
        {"quanpin-helpcode", "全拼辅助码"},
        {"quanpin-helpcode-schema", "全拼辅助码方案"},
        {"shuangpin-helpcode", "双拼辅助码"},
        {"shuangpin-helpcode-schema", "双拼辅助码方案"},
        {"frequency-adjustment", "调频方式"},
        {"frequency-trigger-count", "调频触发次数"},
        {"frequency-linear-step", "线性调频步长"},
        {"unicode-mode", "Unicode 模式"},
        {"super-jianpin-mode", "超级简拼模式"},
        {"temporary-english-mode", "临时英文模式"},
        {"temporary-japanese-mode", "临时日文模式"},
        {"mixed-english-candidates", "混合英文候选"},
        {"mixed-english-minimum-prefix", "英文最短前缀"},
        {"mixed-emoji-candidates", "混合 Emoji 候选"},
        {"mixed-kaomoji-candidates", "混合颜文字候选"},
        {"clipboard-history", "剪贴板历史"},
        {"floating-toolbar", "悬浮工具栏"},
        {"voice-enabled", "启用语音输入"},
        {"voice-provider", "语音服务商"},
        {"voice-credential", "语音 API 令牌"},
        {"voice-credential-clear", "清除已保存的语音令牌"},
        {"voice-endpoint", "语音服务地址"},
        {"voice-model", "语音模型"},
        {"voice-language", "语音语言"},
        {"voice-polish-enabled", "启用语音文本润色"},
        {"voice-polish-endpoint", "润色服务地址"},
        {"voice-polish-model", "润色模型"},
        {"voice-polish-prompt", "润色提示词"},
        {"cloud-enabled", "云候选"},
        {"connect-timeout-ms", "连接超时（毫秒）"},
        {"total-timeout-ms", "总超时（毫秒）"},
        {"ai-enabled", "AI 联想"},
        {"ai-provider", "AI 服务商"},
        {"ai-credential", "AI API 令牌"},
        {"ai-credential-clear", "清除已保存的 AI 令牌"},
        {"ai-endpoint", "AI 服务地址"},
        {"ai-model", "AI 模型"},
        {"ai-prompt", "AI 提示词"},
        {"ai-candidate-limit", "AI 候选数"},
        {"translation-enabled", "候选翻译"},
        {"translation-provider", "翻译服务商"},
        {"translation-credential", "翻译 API 令牌"},
        {"translation-credential-clear", "清除已保存的翻译令牌"},
        {"translation-target-language", "翻译目标语言"},
        {"translation-endpoint", "翻译服务地址"},
    };
    const auto found = labels.find(row.id);
    return found == labels.end() ? row.label.c_str() : found->second;
}

} // namespace metasequoia::linux_ime
